# --- MATD3 specific parameters ---

runner: "episode"

buffer_size: 50000
# update the target network every {} episodes
target_update_interval_or_tau: .005

obs_agent_id: True
obs_last_action: False
obs_individual_obs: False

critic_individual_obs: True
critic_last_action: False
critic_agent_id: True

# use the madddpg_learner to train
mac: "maddpg_mac"
reg: 0.001
batch_size: 32
lr: 0.0003
use_rnn: True

standardise_returns: False
standardise_rewards: True

learner: "matd3_learner"
agent_output_type: "pi_logits"
hidden_dim: 128
critic_type: "maddpg_critic"

optim_type: "adam"
actor_freq: 2
name: "matd3"

