# --- Multi-Task MATD3+BC specific parameters ---

runner: "mt_episode"

buffer_size: 50000
# update the target network every {} episodes
target_update_interval_or_tau: .005

obs_agent_id: True
obs_last_action: True
obs_individual_obs: True

critic_individual_obs: True
critic_last_action: False
critic_agent_id: True

# mac
mac: "mt_maddpg_mac"
batch_size: 32
lr: 0.0003

standardise_returns: False
standardise_rewards: True

# agent type
agent: "mt_rnn"

learner: "mt_matd3_learner"
agent_output_type: "pi_logits"
hidden_dim: 128
critic_type: "mt_maddpg_critic"


# params about observation decomposition
id_length: 4
max_agent: 15


# params about mt mixing network
entity_embed_dim: 64
attn_embed_dim: 8
head: 1

optim_type: "adam"
actor_freq: 2
td3_alpha: 2.5

name: "mt_matd3_bc"

