# --- OMAR specific parameters ---

action_selector: "multinomial"
epsilon_start: .5
epsilon_finish: .05
epsilon_anneal_time: 500000
mask_before_softmax: True

runner: "parallel"

batch_size_run: 8 # batch_size_run=4, buffer_size = 2500, batch_size=64  for 3s5z_vs_3s6z

buffer_size: 32
batch_size: 128

# env_args:
#   state_last_action: False # critic adds last action internally

# update the target network every {} training steps
target_update_interval_or_tau: 200


lr: 0.001
critic_lr: 0.001
td_lambda: 0.6
cql_alpha: 5.0

critic_hidden_dim: 256

omar_iters: 5
omar_coe: 0.5
omar_num_samples: 10
# use qmix
mixing_embed_dim: 32

# use COMA
agent_output_type: "pi_logits"
learner: "omar_learner"


name: "omar"