wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    code_path: code/src/main.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    python_version: 3.10.11
    start_time: 1698840270.078981
    t:
      1:
      - 1
      - 52
      - 55
      2:
      - 1
      - 52
      - 55
      3:
      - 13
      - 16
      - 23
      - 35
      4: 3.10.11
      5: 0.13.11
      8:
      - 2
      - 5
      9:
        2: offpymarl
action_selector:
  desc: null
  value: epsilon_greedy
agent:
  desc: null
  value: rnn
agent_output_type:
  desc: null
  value: q
batch_size:
  desc: null
  value: 32
batch_size_run:
  desc: null
  value: 1
buffer_cpu_only:
  desc: null
  value: true
buffer_size:
  desc: null
  value: 5000
checkpoint_path:
  desc: null
  value: ''
cql_alpha:
  desc: null
  value: 1.0
cql_type:
  desc: null
  value: base
critic_lr:
  desc: null
  value: 0.0005
device:
  desc: null
  value: cuda
double_q:
  desc: null
  value: true
env:
  desc: null
  value: sc2
env_args:
  desc: null
  value:
    continuing_episode: false
    debug: false
    difficulty: '7'
    game_version: null
    heuristic_ai: false
    heuristic_rest: false
    map_name: 3m
    move_amount: 2
    obs_all_health: true
    obs_instead_of_state: false
    obs_last_action: false
    obs_own_health: true
    obs_pathing_grid: false
    obs_terrain_height: false
    obs_timestep_number: false
    replay_dir: ''
    replay_prefix: ''
    reward_death_value: 10
    reward_defeat: 0
    reward_negative_scale: 0.5
    reward_only_positive: true
    reward_scale: true
    reward_scale_rate: 20
    reward_sparse: false
    reward_win: 200
    seed: 0
    state_last_action: true
    state_timestep_number: false
    step_mul: 8
epsilon_anneal_time:
  desc: null
  value: 50000
epsilon_finish:
  desc: null
  value: 0.05
epsilon_start:
  desc: null
  value: 1.0
evaluate:
  desc: null
  value: false
gamma:
  desc: null
  value: 0.99
grad_norm_clip:
  desc: null
  value: 10
hypernet_embed:
  desc: null
  value: 64
hypernet_layers:
  desc: null
  value: 2
label:
  desc: null
  value: default_label
learner:
  desc: null
  value: q_learner
learner_log_interval:
  desc: null
  value: 250
load_step:
  desc: null
  value: 0
local_results_path:
  desc: null
  value: results
log_interval:
  desc: null
  value: 250
lr:
  desc: null
  value: 0.0005
mac:
  desc: null
  value: basic_mac
map_name:
  desc: null
  value: 3m
mixer:
  desc: null
  value: qmix
mixing_embed_dim:
  desc: null
  value: 32
name:
  desc: null
  value: qmix_cql
obs_agent_id:
  desc: null
  value: true
obs_last_action:
  desc: null
  value: true
offline_batch_size:
  desc: null
  value: 32
offline_bottom_data_path:
  desc: null
  value: ''
offline_data_folder:
  desc: null
  value: dataset
offline_data_quality:
  desc: null
  value: expert
offline_data_shuffle:
  desc: null
  value: false
offline_data_type:
  desc: null
  value: h5
offline_max_buffer_size:
  desc: null
  value: 4000
optim_alpha:
  desc: null
  value: 0.99
optim_eps:
  desc: null
  value: 1.0e-05
optim_type:
  desc: null
  value: Adam
remark:
  desc: null
  value: ''
repeat_id:
  desc: null
  value: 1
results_save_dir:
  desc: null
  value: /home/zzq/Project/GitProject/offpymarl/results/offline/2023-11-01/sc2/3m/expert/qmix_cql/seed_0_20:04:26
resume_id:
  desc: null
  value: null
rnn_hidden_dim:
  desc: null
  value: 64
run_file:
  desc: null
  value: offline
runner:
  desc: null
  value: episode
runner_log_interval:
  desc: null
  value: 250
save_model:
  desc: null
  value: true
save_model_interval:
  desc: null
  value: 10000
save_replay:
  desc: null
  value: false
seed:
  desc: null
  value: 0
standardise_returns:
  desc: null
  value: false
standardise_rewards:
  desc: null
  value: false
t_max:
  desc: null
  value: 40000
target_update_interval_or_tau:
  desc: null
  value: 0.01
test_greedy:
  desc: null
  value: true
test_interval:
  desc: null
  value: 250
test_nepisode:
  desc: null
  value: 32
unique_token:
  desc: null
  value: seed_0_20:04:26
use_cuda:
  desc: null
  value: true
use_tensorboard:
  desc: null
  value: false
use_wandb:
  desc: null
  value: true
wandb_project_name:
  desc: null
  value: offpymarl
weight_decay:
  desc: null
  value: 0
